name: Run bots

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Run bots
      run: python rpsrunner.py -m 100 -t 8 'bots/*.py'
